server:
  port: 9096

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # http://localhost:9096/config-client/default/main
          uri: https://github.com/great-jin/eureka-config
          skip-ssl-validation: true
