server:
  port: 9091

spring:
  application:
    name: client-1
  cloud:
    # Monitor console
    consul:
      host: localhost
      port: 9190

eureka:
  client:
    serviceUrl:
      # 在指定服务中心注册自己
      defaultZone: http://localhost:9090/eureka/